// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwxOi9kNf9lJNklGrs1KNRAEPM3g00Rg',
    appId: '1:1096807941:web:462c0139c167e9950b8e6c',
    messagingSenderId: '1096807941',
    projectId: 'cmsc23-todo-app-pdfuentes',
    authDomain: 'cmsc23-todo-app-pdfuentes.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-pdfuentes.appspot.com',
    measurementId: 'G-W8CFKP853V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4C4FquVoFblRSeWRcTEAEQvwttL8oMsE',
    appId: '1:1096807941:android:07573a2c0b51f9a00b8e6c',
    messagingSenderId: '1096807941',
    projectId: 'cmsc23-todo-app-pdfuentes',
    storageBucket: 'cmsc23-todo-app-pdfuentes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh069RsyFWkcAT8RDSz8vOfY0qFCoZZ2s',
    appId: '1:1096807941:ios:7181b52430dd44540b8e6c',
    messagingSenderId: '1096807941',
    projectId: 'cmsc23-todo-app-pdfuentes',
    storageBucket: 'cmsc23-todo-app-pdfuentes.appspot.com',
    iosClientId: '1096807941-h3bc2r91rimlvu0cml9am8b2ddd29bri.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh069RsyFWkcAT8RDSz8vOfY0qFCoZZ2s',
    appId: '1:1096807941:ios:7181b52430dd44540b8e6c',
    messagingSenderId: '1096807941',
    projectId: 'cmsc23-todo-app-pdfuentes',
    storageBucket: 'cmsc23-todo-app-pdfuentes.appspot.com',
    iosClientId: '1096807941-h3bc2r91rimlvu0cml9am8b2ddd29bri.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
